INSERT INTO login_doctors VALUES (NULL ,1 , "aanya123", "123aanya" );
INSERT INTO login_doctors VALUES (NULL ,2 , "sunita89", "ugihygt67" );
INSERT INTO login_doctors VALUES (NULL ,3 , "rishab_85", "nbhgfty78" );
INSERT INTO login_doctors VALUES (NULL ,4 , "jyotis0", "ghyu767" );
INSERT INTO login_doctors VALUES (NULL ,5 , "jyoti90", "fgty809" );
INSERT INTO login_doctors VALUES (NULL ,6 , "priya_06", "bghyu09u" );
INSERT INTO login_doctors VALUES (NULL ,7 , "komal_0008", "bgfhyui89" );
INSERT INTO login_doctors VALUES (NULL ,8, "jogi89", "890hghgfh" );
INSERT INTO login_doctors VALUES (NULL , 9, "anayyyy", "bfdgyu90" );
INSERT INTO login_doctors VALUES (NULL , 10 , "jiten78g", "cft567" );
INSERT INTO login_doctors VALUES (NULL ,11 , "anitaa67", "ccvyy67f" );
INSERT INTO login_doctors VALUES (NULL ,12 , "abhi98", "1320abhi" );
INSERT INTO login_doctors VALUES (NULL , 14, "bhunesh", "bhu2020" );
INSERT INTO login_doctors VALUES (NULL ,15 , "ishan20", "bnju89" );
INSERT INTO login_doctors VALUES (NULL ,13 , "shashwat90", "test123" );
INSERT INTO login_doctors VALUES (NULL ,16 , "ankitt67", "bvcfdty789" );
INSERT INTO login_doctors VALUES (NULL , 17, "rohan78", "cvfgtyu78" );
INSERT INTO login_doctors VALUES (NULL , 18, "amita5789", "bvcxdfty90" );
INSERT INTO login_doctors VALUES (NULL ,19 , "deba789", "mnbhgvf78" );
INSERT INTO login_doctors VALUES (NULL , 20, "mukesh678", "nbvg909h" );
