INSERT INTO login_pharmacies VALUES ( NULL , 1, "aman98 ", " 1213ee3fec");
INSERT INTO login_pharmacies VALUES ( NULL ,2 , " ajaystar5", "h76fgdyue677");
INSERT INTO login_pharmacies VALUES ( NULL ,3, "bip90_p ", "bhde78ddehd");
INSERT INTO login_pharmacies VALUES ( NULL ,4 , " ajay89yp", "podd9wdwcc");
INSERT INTO login_pharmacies VALUES ( NULL ,5 , "adi_098 ", "vghedhedd");
INSERT INTO login_pharmacies VALUES ( NULL , 6, "ali_mu78 ", "Ali_scsc");
INSERT INTO login_pharmacies VALUES ( NULL ,7 , "rishab_5", "12345678");
INSERT INTO login_pharmacies VALUES ( NULL ,8 , "porty", "ferjferfrfv");
INSERT INTO login_pharmacies VALUES ( NULL , 9, "pefee", "poko398");
INSERT INTO login_pharmacies VALUES ( NULL ,10 , "ratyu", "09opfefe");
INSERT INTO login_pharmacies VALUES ( NULL ,11 , "rtyui_09", "dkncjeverf90");
INSERT INTO login_pharmacies VALUES ( NULL ,12 , "gamer_09", "test123");
INSERT INTO login_pharmacies VALUES ( NULL , 13, "potri_0", "pwweofjewf");
INSERT INTO login_pharmacies VALUES ( NULL , 14, "abhi_908", "abhwwefeifec");
INSERT INTO login_pharmacies VALUES ( NULL , 15, "122e_po", "bdlwfjwef9i23e");
INSERT INTO login_pharmacies VALUES ( NULL ,16 , "xdfg_09", "cdjf9fe0f");
INSERT INTO login_pharmacies VALUES ( NULL ,17 , "aditi_98", "eeferf90");
INSERT INTO login_pharmacies VALUES ( NULL ,18 , "prnv_07", "mfewof90");
INSERT INTO login_pharmacies VALUES ( NULL , 19, "gaurav57", "90uhhjjo");
INSERT INTO login_pharmacies VALUES ( NULL , 20, "chotu89", "78hifrvr");
