INSERT INTO login_clinics VALUES (NULL , 1, "bakul90", "sd" );
INSERT INTO login_clinics VALUES (NULL ,2 , "chamn89", "anjhduad" );
INSERT INTO login_clinics VALUES (NULL ,3 , "anu_87", "n bashydu3" );
INSERT INTO login_clinics VALUES (NULL , 4, "anujj89", "nbchjds678" );
INSERT INTO login_clinics VALUES (NULL ,5 , "pushpa55", "nhjdyuas7" );
INSERT INTO login_clinics VALUES (NULL ,6 , "chavi4654", "dhgauda89" );
INSERT INTO login_clinics VALUES (NULL , 7, "rushil_09", "njhf89" );
INSERT INTO login_clinics VALUES (NULL , 8, "dipti88", "hgfdrety567" );
INSERT INTO login_clinics VALUES (NULL ,9 , "dfgty", "vcfdg5678" );
INSERT INTO login_clinics VALUES (NULL ,10 , "deepa09", "jhbfuyei8349" );
INSERT INTO login_clinics VALUES (NULL ,11 , "chirag0989", "bndftfy7657" );
INSERT INTO login_clinics VALUES (NULL ,12 , "shamklp", "098923hjwef" );
INSERT INTO login_clinics VALUES (NULL , 13, "shivam34", "test123" );
INSERT INTO login_clinics VALUES (NULL ,14 , "yash98", "nbhjasuid8a9" );
INSERT INTO login_clinics VALUES (NULL , 15, "prem_043", "mjhsf78" );
INSERT INTO login_clinics VALUES (NULL , 16, "yami89", "09283ug3t" );
INSERT INTO login_clinics VALUES (NULL , 17, "alka89", "jhbhauif89e1" );
INSERT INTO login_clinics VALUES (NULL ,18 , "manish76", " nabhduia9" );
INSERT INTO login_clinics VALUES (NULL ,19 , "priti999", "ncbhgcyus7684" );
INSERT INTO login_clinics VALUES (NULL ,20 , "virdas69", "hgdyawur87" );
