INSERT INTO clinics VALUES(NULL,"Suman Clinic","9/4, Tata Blocks, Sir Ratan Tata Road, Tardeo","123456701");
INSERT INTO clinics VALUES(NULL,"Aman Clinic","605, H Patel Nagar, M G X Road-2, Kandivli(w)","123456789");
INSERT INTO clinics VALUES(NULL,"Shona Clinic","100/102, Nagdevi Street, Mandvi","128632749");
INSERT INTO clinics VALUES(NULL,"Aadarsh Clinic","Chemical Developmt Compd, Ghodbunder Road, Manpada, Thane (west)","783456789");
INSERT INTO clinics VALUES(NULL,"Shashi Clinic","2, Silver Arch, Near Hritik Hotel, Ramnagar, Borivali (west)","543456789");
INSERT INTO clinics VALUES(NULL,"Mohan Clinic","Nr S T Stand Geeta Mandir, Raipur","853456789");
INSERT INTO clinics VALUES(NULL,"Jiten Clinic","Nral Stores Ma, Kothrud","121556789");
INSERT INTO clinics VALUES(NULL,"Anvit Clinic","Shop-13, Sukh Sagar Society, Goddev Road, Opp. Vini Country Bar, Bhayander (east)","123456239");
INSERT INTO clinics VALUES(NULL,"Anchal Clinic","233 Arun Chambers, M Malaviya Road, Delisle Road","123276789");
INSERT INTO clinics VALUES(NULL,"Jiten Clinic","6, Rna Arcade, Opp Oriental Bank,lokhandwala Cplx, Andheri (west)","129856789");
INSERT INTO clinics VALUES(NULL,"Nita Clinic","4-1-917, Parsi Lane, Tilak Road","123450389");
INSERT INTO clinics VALUES(NULL,"Shashank Clinic","5, Babu Mistri Chawl, Station Rd, Bhayander (west)","189456789");
INSERT INTO clinics VALUES(NULL,"Riya Clinic","15/17, Old Hanuman Lane, Ladwadi, Kalbadevi","199956789");
INSERT INTO clinics VALUES(NULL,"Bhavin Clinic","2, Anand Bhavan, Hirachand Desai Road, Next To Bata Showroom, Ghatkopar (west)","623456789");
INSERT INTO clinics VALUES(NULL,"Ishika Clinic","Govt Industrial Estate, Kandivali (west)","999956789");
INSERT INTO clinics VALUES(NULL,"Abhishek Clinic","U 8","120156789");
INSERT INTO clinics VALUES(NULL,"Arun Clinic","A 45, Nand Kishore Indl. Et., Off Mahakali Caves Road, Chakala, Andheri (west)","123856789");
INSERT INTO clinics VALUES(NULL,"Anjali Clinic","505 5th Floor, Popatlal Chambers, 4th Clive Cross Lane, Masjid Bunder(e)","123456469");
INSERT INTO clinics VALUES(NULL,"Amrita Clinic","Shop No 4, Ganga Smruti Bldg, Bp Road, Bhayander (east)","998456789");
INSERT INTO clinics VALUES(NULL,"Neha Clinic","Opp Ahmedabad College, Gheekanta","888886789");
